name: Collect RSS Feeds

on:
  workflow_dispatch:  # 手動実行用トリガー

permissions:
  contents: write 

jobs:
  collect:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install feedparser pandas

    - name: Run RSS collector
      run: python rss_crawler.py

    - name: Commit results
      run: |
        git config --global user.name 'rss-bot'
        git config --global user.email 'rss@example.com'
        git pull --rebase origin main
        git add logs/*.csv
        git commit -m "Update RSS logs"
        git push
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

