name: Collect RSS Feeds

on:
  schedule:
    - cron: "0 */3 * * *"  # 3時間おきに実行
  workflow_dispatch:

jobs:
  collect:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser pandas requests beautifulsoup4

      - name: Run RSS collector
        run: python rss_crawler.py

      - name: Commit results
        run: |
          git config --global user.name 'rss-bot'
          git config --global user.email 'rss-bot@example.com'
          git pull --rebase --autostash || true
          git add logs/
          git commit -m "Update RSS logs" || echo "No changes to commit"
          git push
